### ISSUE TITLE
Can't install NuGet package to a project

### ISSUE THREAD

**Issue by koshkarov** [endless-qa/nunit-test-video-recorder#2]
Hi Viktor, 

first of all thank you for your work! 

But when I tried to install your package it throws the error: 
> Could not install package 'Nunit.Video.Recorder 1.0.0'. You are trying to install this package into a project that targets 
> '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more 
> information, contact the package author.

![2018-01-30 00_06_46 - microsoft visual studio](https://user-images.githubusercontent.com/7766436/35549200-5e5d3410-0552-11e8-9c25-3de5ee322077.jpg)

It looks like this has something to do with how was the NuGet package created and it doesn't support assemblies with this version of .Net Framework.

Could you please take a look at it? 

Thank you.

**Comment by endless-qa** [comment]
Hi,

Thanks for using it!

The minimal supported version of the .Net framework is **4.5.2**. There are 3 possible ways to fix the issue:
1. Either changing a target framework version of your test project to the 4.5.2. Which is a really fast way, if it's not critical for your code (shouldn't be if it's a project with the test code only).
2. Or I need to change it for the Video Recorder project, then re-pack everything for NuGet and re-upload.
3. Or I can change a target version locally, then build binaries and send them to you. By the way, you can easily do the same by cloning the project repository, changing its target version and building by yourself.

However, I'd recommend you to try the first option. Here is how you can change a target version:
- select your project in the Solution Explorer;
- open its Properties via the Context Menu (or Alt+Enter);
- in the opened window, there is the Application tab. There is the Target Framework drop-down list there;
- select .NET Framework 4.5.2, confirm the change in the popup dialogue and that's it.

Your project will be re-opened and you will be able to install the NUnit Video Recorder through NuGet Package Manager.

Please let me know, what option is the best for you and if everything works fine if you decide to apply the solution above.

**Comment by koshkarov** [comment]
Hi Viktor,

yes, I wouldn't ask you to repack just because of my project. :) 
I'll take a look for two other options.  

Thank you, you are very helpful!
